import "./globals.css";
import { Inter } from "next/font/google";

interface RootLayoutProps extends React.HTMLAttributes<HTMLBodyElement> {}
interface MetaData extends React.HTMLAttributes<HTMLMetaElement> {
  description: string;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: MetaData = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
